### ISSUE TITLE
Python 3.8 'time.clock()' removed

### ISSUE THREAD

**Issue by LexiconCode** [daanzu/kaldi-active-grammar#15]
Python: 3.8
Caster: (Py 3 pull request)
kaldi_module_loader_plus: latest dragonfly master
kaldi_active_grammar: 1.2

```
Traceback (most recent call last):
  File "kaldi_module_loader_plus.py", line 156, in <module>
    main()
  File "kaldi_module_loader_plus.py", line 150, in main
    engine.do_recognition(on_begin, on_recognition, on_failure)
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python38\lib\site-packages\dragonfly\engines\base\engine.py", line 242, in do_recognition
    self._do_recognition(*args, **kwargs)
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python38\lib\site-packages\dragonfly\engines\backend_kaldi\engine.py", line 309, in _do_recognition
    self._decoder.decode(block, False, kaldi_rules_activity)
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python38\lib\site-packages\kaldi_active_grammar\wrapper.py", line 445, in decode
    self._start_decode_time(len(frames))
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python38\lib\site-packages\kaldi_active_grammar\wrapper.py", line 64, in _start_decode_time
    self.decode_start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

`time.clock()` has been deprecated since Python 3.3
- See [issue](https://bugs.python.org/issue36895)
- Recommended to use: `time.perf_counter()` or `time.process_time()` for py3
- Not sure about a py2/py3 solution using the six or other compatibility library.

**Comment by daanzu** [comment]
Thanks! Should be fixed in master and the next version.
