### ISSUE TITLE
Version lock NumPy to `1.19.3`

### ISSUE THREAD

**Issue by LexiconCode** [daanzu/kaldi-active-grammar#44]
There is an ongoing [issue](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html) with NumPy 1.19.4  specific to Windows 10, version 20H2 and Windows Server, version 20H2 with AMD processors.

Downgrading `pip install numpy==1.19.3` fixes the issue.

```
ERROR:engine.kaldi:Exception during import of Kaldi engine module: The current Numpy installation ('C:\\Users\\Main\\Desktop\\Caster3-Test-Kaldi-py3-64bit\\WPy64-3860\\python-3.8.6.amd64\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
Traceback (most recent call last):
  File "C:\Users\Main\Desktop\Caster3-Test-Kaldi-py3-64bit\WPy64-3860\python-3.8.6.amd64\lib\site-packages\dragonfly\engines\backend_kaldi\__init__.py", line 51, in is_engine_available
    from .engine import KaldiEngine
  File "C:\Users\Main\Desktop\Caster3-Test-Kaldi-py3-64bit\WPy64-3860\python-3.8.6.amd64\lib\site-packages\dragonfly\engines\backend_kaldi\engine.py", line 30, in <module>
    import kaldi_active_grammar
  File "C:\Users\Main\Desktop\Caster3-Test-Kaldi-py3-64bit\WPy64-3860\python-3.8.6.amd64\lib\site-packages\kaldi_active_grammar\__init__.py", line 22, in <module>
    from .wrapper import KaldiAgfNNet3Decoder, KaldiPlainNNet3Decoder
  File "C:\Users\Main\Desktop\Caster3-Test-Kaldi-py3-64bit\WPy64-3860\python-3.8.6.amd64\lib\site-packages\kaldi_active_grammar\wrapper.py", line 17, in <module>
    import numpy as np
  File "C:\Users\Main\Desktop\Caster3-Test-Kaldi-py3-64bit\WPy64-3860\python-3.8.6.amd64\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\Main\Desktop\Caster3-Test-Kaldi-py3-64bit\WPy64-3860\python-3.8.6.amd64\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\Main\\Desktop\\Caster3-Test-Kaldi-py3-64bit\\WPy64-3860\\python-3.8.6.amd64\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity
```

**Comment by daanzu** [comment]
Gah, thanks for notifying me of this! I ran into this problem a while back (even though I run Intel) unrelated to KaldiAG, but didn't realize its implications here. (I also am amazed they haven't fixed it yet.) I will push a temporary fix.

**Comment by daanzu** [comment]
I uploaded a new wheel just for windows: v1.8.3. Please let me know if it works or not.

**Comment by LexiconCode** [comment]
I was impressed that it's not fixed given the popularity of Numpy. The kaldi active grammar package installs as expected now.
