### ISSUE TITLE
Python 3 bug when make_lexicon_fst.py is run

### ISSUE THREAD

**Issue by Danesprite** [daanzu/kaldi-active-grammar#5]
Hey @daanzu. I've discovered a bug specific to Python 3 that occurs when first running the Dragonfly Kaldi module loader. I've posted here instead because it seems to be a KAG bug caused by running the `make_lexicon_fst.py` script with `python` instead of `python3`. `python` is Python 2.7 on my system, which would explain the confusing `SyntaxError`.

Not sure how to fix this. I guess you need to use the interpreter's commandline path instead?

```
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/kaldi/make_lexicon_fst.py", line 78
    sys.argv[0], line.strip(" \t\r\n"), filename), file=sys.stderr)
                                                       ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "kaldi_module_loader.py", line 101, in <module>
    main()
  File "kaldi_module_loader.py", line 82, in main
    engine.connect()
  File "/home/dane/repos/dragonfly/dragonfly/engines/backend_kaldi/engine.py", line 123, in connect
    cloud_dictation_lang=self._options['cloud_dictation_lang'],
  File "/home/dane/repos/dragonfly/dragonfly/engines/backend_kaldi/compiler.py", line 73, in __init__
    KaldiAGCompiler.__init__(self, model_dir=model_dir, tmp_dir=tmp_dir, **kwargs)
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/compiler.py", line 190, in __init__
    self.model = Model(model_dir, tmp_dir)
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/model.py", line 197, in __init__
    self.generate_lexicon_files()
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/model.py", line 301, in generate_lexicon_files
    command()
  File "/home/dane/.local/lib/python3.7/site-packages/ush.py", line 585, in __call__
    return wait(procs, raise_on_error)
  File "/home/dane/.local/lib/python3.7/site-packages/ush.py", line 189, in wait
    result = tuple(iterate_outputs(procs, raise_on_error, status_codes))
  File "/home/dane/.local/lib/python3.7/site-packages/ush.py", line 221, in iterate_outputs
    raise ProcessError(process_info)
ush.ProcessError: One or more commands failed: [(['python', '/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/kaldi/make_lexicon_fst.py', '--left-context-phones=kaldi_model_zamia/left_context_phones.txt', '--nonterminals=kaldi_model_zamia/nonterminals.txt', '--sil-prob=0.5', '--sil-phone=SIL', '--sil-disambig=#14', 'kaldi_model_zamia/lexiconp_disambig.txt'], 24795, 1), (['/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/exec/linux/fstcompile', '--isymbols=kaldi_model_zamia/phones.txt', '--osymbols=kaldi_model_zamia/words.txt', '--keep_isymbols=false', '--keep_osymbols=false'], 24796, 0), (['/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/exec/linux/fstaddselfloops', 'kaldi_model_zamia/wdisambig_phones.int', 'kaldi_model_zamia/wdisambig_words.int'], 24797, 0), (['/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/exec/linux/fstarcsort', '--sort_type=olabel'], 24798, 0)]

```

**Comment by M3TIOR** [comment]
It's a bug resulting from the python version which is calling the script, not transfering the correct version to the target the script. The script is currently calling the binary at "python" and assuming it's the correct version. Awaiting a merge of my pull request #6 to fix this issue. It's litterally a one line problem, so @daanzu may choose not to pull my fix, but regardless it should be cleared up soon.
